name: Test

on: [push, pull_request]

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build and Check
      id: makepkg
      uses: ./
    - name: Upload Package Archive (zipped by GH)
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.makepkg.outputs.pkgfile0 }}
        path: ${{ steps.makepkg.outputs.pkgfile0 }}
